version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sw1_casetool_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=supabase
      - JWT_SECRET=SW1_PrimerParcial_CASE_Tool_Security_Key_2026_UAGRM_FICCT_UltraSecureKey_998877
    restart: unless-stopped
    networks:
      - casetool_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sw1_casetool_frontend
    ports:
      - "80:80"
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - casetool_net

networks:
  casetool_net:
    driver: bridge
